export { default } from "./src/wallet-manager-multisig-solana-squads.js";
export { default as WalletAccountMultisigSolanaSquads } from "./src/wallet-account-multisig-solana-squads.js";
export { NotSupportedError } from "./src/errors.js";
export type MultisigInfo = import("@tetherto/wdk-wallet/multisig").MultisigInfo;
export type MultisigProposal = import("@tetherto/wdk-wallet/multisig").MultisigProposal;
export type MultisigMessageProposal = import("@tetherto/wdk-wallet/multisig").MultisigMessageProposal;
export type MultisigAutoExecuteResult = import("@tetherto/wdk-wallet/multisig").MultisigAutoExecuteResult;
export type MultisigTransactionOptions = import("@tetherto/wdk-wallet/multisig").MultisigTransactionOptions;
export type MultisigOptions = import("@tetherto/wdk-wallet/multisig").MultisigOptions;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type SimpleSolanaTransaction = import("@tetherto/wdk-wallet-solana").SimpleSolanaTransaction;
export type SolanaTransactionReceipt = import("@tetherto/wdk-wallet-solana").SolanaTransactionReceipt;
export type SolanaMultisigSquadsCommonConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsCommonConfig;
export type SolanaMultisigSquadsSigningConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsSigningConfig;
export type SolanaMultisigSquadsConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsConfig;
export type SolanaMultisigSquadsReadOnlyConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsReadOnlyConfig;
export type SolanaMultisigInfo = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigInfo;
export type SolanaMultisigProposal = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigProposal;
export type SolanaMultisigProposalResult = import("./src/wallet-account-multisig-solana-squads.js").SolanaMultisigProposalResult;
export { default as WalletAccountReadOnlyMultisigSolanaSquads, SQUADS_PROGRAM_ADDRESS } from "./src/wallet-account-read-only-multisig-solana-squads.js";
